### ISSUE TITLE
design ui {views prototypes}

### ISSUE THREAD

**Issue by aSlug** [buildo/yelpydelpy#2]
- [x] creare prototipo per research view
- [x] creare prototipo per details view

**Comment by raasoft** [comment]
Ottimo, quando sei pronto per cominciare a lavorarci, spostalo in WIP dalla kanban (o dal project Training & Evaluation)

**Comment by aSlug** [comment]
[Qui](https://paper.dropbox.com/doc/yelpydelpy-views-prototypes--AsfpuM7Zrk1RfEzFRMKHVUgxAg-7lNYNnKsYwJfQuWigCgk8) il prototipo deciso per la UI
