### ISSUE TITLE
bootstrap applicazione {scaffold dell'app pronto}

### ISSUE THREAD

**Issue by aSlug** [buildo/yelpydelpy#3]
Scarico tutti i tool necessari, preparo l'ambiente e genero uno scaffold funzionante dell'applicazione.

**Comment by raasoft** [comment]
Ciao @aSlug, sono in review ma non capisco cosa devo revieware. Potresti aiutarmi?

**Comment by aSlug** [comment]
> Ciao @aSlug, sono in review ma non capisco cosa devo revieware. Potresti aiutarmi?

Se domani facciamo un rapidissimo check di come ho strutturato l'app possiamo chiudere questo task
